title: TimeMap#3
tags: Modern Dance, Projection Mapping, Infrared Tracking, Interactive, Set Design, OpenFrameworks
partners: Jonas Jongejan, Tina Tarpgaard
client: Recoil Performance Group
date: April 2009
materials: Infrared camera, videoprojectors, custom software.
github: {'user':'RecoilPerformanceGroup','repo':Livingroom'}
lead: Typing, sampling and tracking dance.  
photocredits: Søren Meisner
appearances: 
  - 
    date: April 2009
    occasion: Premiere 
    place: Dansehallerne, Copenhagen
    url: http://www.recoil-performance.org/productions/timemap-3

content: |
 Time Map is a dance performance that is sampled, manipulated and reconstructed, as if you where in a film set and part of a live editing process.
 In this time displaced universe 3 people meet. Ottilia 1886, Rose 2008, Keem 2258 – each of them seeking to find justice.
 The three dancers have worked from a base of true stories from past, present and future.
 Being placed in past, present and future their stories are portrayed visually, physically and dramatically.
 They meet in the court room in a battle with words – from taking orders to making them fly across the screens.

 Ole Kristensen and Jonas Jongejan created the videoscenography using infrared motion tracking implemented in openFrameworks. All video and lights were cued from qLab using midi to Isadora through to a GrandMA node, our own custom OSC server, openGL renderer and scene and text editor. During the performance all text was typed live by the author Gritt Uldall on stage. The choreographer had control over some of the scenes from her own laptop. Some parts of the first act were filmed and edited on stage during second act for an epilogue shown in the lobby.