title: Body Navigation
tags: Modern Dance, Projection, Infrared Tracking, Interactive, Set Design, Featured, Processing
partners: Jonas Jongejan, Tina Tarpgaard
client: Recoil Performance Group
date: May 2008
materials: Infrared camera, videoprojector, Processing code.
lead: Tracking dance in Recoil Performance Group.  
content: |
  A reactive floorprojection for a Recoil Performance Group dance performance/installation. I developed this in collaboration with choreographer Tina Tarpgaard and programmer Jonas Jongejan.

  Two dancers and their digital reproduction are the scenographic frame of this humorous and emotional portrait of human relations. Based on rules and structured in a game like manner, the installation makes way for a playful dialog between the man, woman and the digital “footprints” they leave behind.

  The Body Navigation performance was originally part of a larger installation and modern dance performance in Copenhagen, by Tim Rushton, Danish Dance Theatre called Labyrint.

  We used processing for the infrared blobtracking of the dancers and drawing the open gl graphics. During the performance Tina controlled the whole thing live from an Isadora-based interface via osc.