title: Longing - Fast Forward 
tags: Timelapse, Cinder, Photography, Featured
partners: Annesofie Norn, Daniel Plewe
client: 
materials: Industrial camera, bespoke software, raid system.
date: September 2013
lead: Work in progress in Kullorsuaq, Greenland.
github: {'user':'olekristensen','repo':'LongingFastForward'}
content: |
  Longing - Fast Forward is a long-term art project with the people living on the edge of the Greenland inland-ice.

  From the summer 2012 an automated research station will monitor a small settlement throughout the circle of one year. Based on performative experiments with local participants and structural collection of video and sound, the recordings will shape a large scale audio-visual installation, showing the current inner / human and outer / environmental change of pace.