title: Longing - Fast Forward 
tags: Timelapse, Cinder, Photography, Featured
partners: Annesofie Norn, Daniel Plewe
client: 
date: September 2013
lead: |
  This year I am running an artistic research station in Greenland. I and some friends set it up in Kullorsuaq with the locals. Sometimes I download a still.
content: |
  .