title: Observational Instrument # This is a comment

date: 2015-04-30  # Year-Month-Date, eg. january 3rd 2004 = 2004-01-03

participants: # a list of elements with each three attributes; [name:], [mail:] and [role:]
 -
   name: Karin Søndergaard
   mail: user@server.domain
   role: Associate Professor # eg. Master Student, Advisor, Assistant
 -
   name: Karina Munkholm Madsen
   mail: user@server.domain
   role: Researcher # eg. Master Student, Advisor, Assistant
 - 
   name: Kjell Yngve Petersen
   mail: user@server.domain
   role: Associate Professor # eg. Master Student, Advisor, Assistant
 -
   name: Ole Kristensen
   mail: user@server.domain
   role: Researcher # eg. Master Student, Advisor, Assistant
 -
   name: Imke Wies van Mil
   mail: user@server.domain
   role: Lighting designer # eg. Master Student, Advisor, Assistant
 -
   name: Jesper Kongshaug
   mail: user@server.domain
   role: Lighting designer # eg. Master Student, Advisor, Assistant
 -
   name: Christina Augustesen
   mail: user@server.domain
   role: Lighting designer # eg. Master Student, Advisor, Assistant
 -
   name: Thyge Währens
   mail: user@server.domain
   role: Research Assistant # eg. Master Student, Advisor, Assistant


photocredits: Kjell Yngve Petersen, Ole Kristensen, Imke Wies van Mil, Karin Søndergaard, Karina Munkholm Madsen

videocredits: Rina de Place Bjørn

tags: # relevant keywords. We want to use ITU course codes eg. DCDP-2013E and terms like Master Thesis, and general concepts and themes like eg. Food or Governance
 - Featured
 - Research
 - Architecture
 - Daylight integration


summary: | # Max 50 words - is shown on website and screen presentations (eg. the Atrium Displays) All paragraphs start with two white-spaces.
  This project about the integration of artificial and daylighting is one of four that were conducted as part of the project entitled LED Lighting; Interdisciplinary LED Lighting Research. The research project has been a three-year collaboration between The Royal Danish Academy of Fine Arts; Schools of Architecture, Design and Conservation and The IT University of Copenhagen.
  

abstract: | # Max 150 words - is shown on website
  In this project we have been interested in identifying the qualitative parameters involved in the integration of dynamic artificial lighting and daylight; the latter being already highly dynamic by nature. Our practice-based methodology is based on the design of what we call an ‘observational instrument’. The observational instrument is comprised of an object that has been designed using built-in LEDs connected to dynamic control software. Our studies have been based upon experiential analyses that examine how the dynamic artificial lighting in the observational instrument unfolds during the changing of the daylight situations that are generated by the weather outside. This research employs the concept of coupling between interior and exterior, in order to identify a spectrum of design parameters that are attentive to the relationships between these two dynamic lighting categories. 
  In connection with the experiential analyses we would like to thank Anne Bay, Astrid Espenhain, Astrid Mody, Brian Wendin Ellen Kathrine Hansen, Hugo Mulder, Katja Bülow, Laura Beloff Nanet Mathiasen, Peter Eklund, and Thorbjørn Lausten for their participation in the experiential interviews. These interviews helped us strengthen our concepts and approaches in relation to the dissemination of the research results provided herein. 
  The book can be downloaded <a href="http://adaptive.itu.dk/content/3.projects/20150430.LEDlys_Instrument/Instrument%20(Book%202:4).pdf">here</a>.
  

legal: 
 - copyright: # the name of the formal copyright holder
 - cc-url: http://creativecommons.org/licenses/by/4.0/ # any valid url to a creative commons licence is encouraged, or you can paste in a raw text of an alternative licence below.
 - non-cc-license-text: | # put the full raw licence if not a creative commons below, eg the MIT licence
    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
   