title: Living Room
tags: Modern Dance, Projection Mapping, Infrared Tracking, Interactive, Set Design, Featured, OpenFrameworks
partners: Jonas Jongejan, Tina Tarpgaard
client: Recoil Performance Group
date: April 2012
materials: Infrared camera, videoprojectors, custom software
github: {'user':'RecoilPerformanceGroup','repo':Livingroom'}
lead: Award winning trompe-d’oil on the dance floor
awards:
 - 
    date: May 2012
    title: Best Dance Performance of the Year
    place: Reumert, the National Danish Theatre Awards
    url: http://www.aaretsreumert.dk/index.dsp?page=5055
photocredits: Søren Meisner
appearances: 
  - 
    date: Dec 2012
    occasion: ICE HOT, Nordic Dance Platform 
    place: Helsinki
    url: http://www.nordicdanceplatform.com/program_on_stage/living_room.html
  - 
    date: Nov 2012
    occasion: Tempel Tanzfestival 
    place: ZKM, Karlsruhe
    url: http://www.kulturverein-tempel.de/index.php?id=356
  - 
    date: Nov 2012
    occasion: Performance 
    place: Dansehallerne, Copenhagen
    url: http://dansehallerne.dk
  - 
    date: April 2012
    occasion: Premiere 
    place: Dansehallerne, Copenhagen
    url: http://dansehallerne.dk

content: |
 Living Room is a performance of an hour with 3 dancers on stage. The projected scenography evolves during the whole performance. Most of the video scenography is made of a polygon world that is randomly generated in the beginning of each performance. During the show it is being crumbled and manipulated live by the dancers.

  For this performance I co-developed the scenographic concept and implemented some new concepts in our software. Most notable a simple method of independently rotating the z-axis of a plane to allow for trompe-d’oil effects of eg. holes in the floor from a movable vantage point in the audience seating. 
  
  The software for Living Room builds further on Cocoa and Objective-C wrapper for openFrameworks; [ofxCocoaPlugins](https://github.com/HalfdanJ/ofxCocoaPlugins). We intergrate [openFrameworks](http://openframeworks.cc) into a cocoa-based Mac OS X Lion application running on a mac pro, seeing the dancers through a Allied Vision Technologies Manta camera, showing the openGL graphics using two video projectors, shooting diagonally onto the white dance floor. The two projectors have 0.7 wide angle optics and the software is qued from qLab using apple’s midi networking capabilities.
