title: Inland
tags: Videography, Installation
partners: Annesofie Norn
date: Nov 2010
materials: Videoprojectors, Tripplehead, Mac mini
lead: Video Triptych from life in the Arctic
photocredits: Ole Kristensen
appearances: 
  - 
    date: Nov 2010
    occasion: Exhibition 
    place: Dansehallerne, Copenhagen
    url: http://dansehallerne.dk

content: |
 This video installation was made to complement the rerun of Frost, a modern dance performance, in Dansehallerne, Copenhagen.

 In the summer of 2009 I travelled up the coast of Nothwestern Greenland with Annesofie Norn in preparation for our project ‘Longing Fast Forward‘. This video installation is based on the footage from this research trip. The installation features Quillaq from the settlement Savissivik

 Frost and Longing Fast Forward are related. I had just returned from Greenland when the choreographer Tina Tarpgaard called me to ask if I could join Frost as software artist – I accepted along with Jonas Jongejan – and we set to work immediately. The performance theme was melting and freezing and the experiences in Greenland inspired quite a share of my work with the interactive scenograpy.
