title: Malpais
tags: Modern Dance, Projection Mapping, Kinect, Interactive, Generative, Set Design, OpenFrameworks
partners: Jonas Jongejan, Tina Tarpgaard
client: Recoil Performance Group
date: March 2011
materials: Kinect, videoprojectors, custom software
github: {'user':'RecoilPerformanceGroup','repo':Malpais'}
lead: Projections of bent voices  
photocredits: Søren Meisner
appearances: 
  - 
    date: March 2011
    occasion: Premiere 
    place: Dansehallerne, Copenhagen
    url: http://dansehallerne.dk
    
content: |
 With an outset in interview material this performance was a departure from our earlier works in Recoil Performance Group. 
 
 My role was to create the visual expression of scenes involving the recorded material as interpreted by the sound artist Pelle Skovmand. One of the elements were elastic sound-waves that would bend around the dancers. Another was a giant, mobile box with a plexiglass backprojection.

 Through documentary style video and a physical research on the anatomy of fear, the performance combines reality, satire and fiction to address one of the most used power tools in history: Our fear.

 The software is open source and we are very grateful to the openFrameworks community, whose efforts form the basis of our programming work. The software for Malpais builds on our move into Cocoa and Objective-C from Fuck You Buddy. We intergrate openFrameworks into a cocoa-based Mac OS X Snow Leopard application running on a mac pro seeing the dancers through a Kinect camera, showing the openGL graphics using a video projector, shooting diagonally onto the white line dance floor. We also built the mobile box with a built-in back projection against a transparent screen, strong enough for the dancers to lean against. The projectors have 0.7 wide angle optics and the software is qued from qLab using apple’s midi networking capabilities.