title: Body Navigation
tags: Modern Dance, Projection Mapping, Infrared Tracking, Interactive, Set Design, Featured, Processing
partners: Jonas Jongejan, Tina Tarpgaard
client: Recoil Performance Group
date: May 2008
materials: Infrared camera, videoprojector, processing code
lead: Tracking dance in Recoil Performance Group
photocredits: Jonas Jongejan
appearances: 
  - 
    date: March 2012
    occasion: Click Festival 
    place: Kulturværftet, Elsinore
    url: http://clickfestival.dk/
  - 
    date: March 2012
    occasion: Mostra Interarte 
    place: Crescer e Viver, Rio de Janiero
    url: http://mostrainterarte.com.br/recoil-design-de-software.html
  - 
    date: Nov 2010
    occasion: Intercity Festival 
    place: Teatro Studio di Scandicci, Florence
    url: http://www.teatrodellalimonaia.it/Limonaia/Intercity/IntHome.html
  - 
    date: Jun 2010
    occasion: Dance Digital 
    place: the Hat Factory, Luton
    url: http://dancedigital.org.uk/2010/03/body-navigation/
  - 
    date: Jan 2010
    occasion: Plaza+ Festival 
    place: Plaza Futura, Eindhoven
    url: http://www.plazaplus.nl/NL/PROGRAMMA&amp;item_id=37
  - 
    date: Nov 2009
    occasion: Ke∂ja 
    place: KHiO, Oslo
    url: http://www.kedja.net/page.asp?page=6
  - 
    date: Dec 2008
    occasion: Performance 
    place: Histrionski dom, Zagreb
    url: #
  - 
    date: May 2008
    occasion: Labyrint 
    place: Kaleidoskop K2, Copenhagen
    url: # 

content: |
  Two dancers and their digital reproduction are the scenographic frame of this humorous and emotional portrait of human relations. Based on rules and structured in a game like manner, the installation makes way for a playful dialog between the man, woman and the digital “footprints” they leave behind.

  The Body Navigation performance was originally part of a larger installation and modern dance performance in Copenhagen, by Tim Rushton, Danish Dance Theatre called Labyrint.

  We used processing for the infrared blobtracking of the dancers and drawing the open gl graphics. During the performance Tina controlled the whole thing live from an Isadora-based interface via osc.
