title: Work in Progress
tags: Installation, Arduino, Electronics, Processing, Generative, Drawing
partners: 
materials: Plotter, arduino, electronics, custom firmware
client: 
photocredits: Ole Kristensen
github: {'user':'olekristensen','repo':'arduinoHPGL'}
date: April 2008
appearances: 
  - 
    date: March 2012
    occasion: Click Festival 
    place: Kulturværftet, Elsinore
    url: http://clickfestival.dk/
  - 
    date: Dec 2011
    occasion: Multiple Market 
    place: Black Box Gallery, Copenhagen
    url: http://www.blackboxgallery.dk/previous.html
  - 
    date: Nov 2010
    occasion: Multiple Market 
    place: Mikrogalleriet, Copenhagen
    url: http://www.blackboxgallery.dk/previous.html
  - 
    date: Nov 2010
    occasion: New Media Days 
    place: Carlsberg, Copenhagen
    url: http://newmediadays.dk/
  - 
    date: Sep 2010
    occasion: Exhibition
    place: Galerie Brunnhofer, Linz
    url: http://www.brunnhofer.at/termine.php?aktiv=134&lang=de&aktuell=1&standort=3&node=328
  - 
    date: Dec 2008
    occasion: Festival
    place: Jul Under Vand, Copenhagen
    url: http://cocreative.com/index.php?page=520
  - 
    date: September 2008
    occasion: Festival
    place: Alt_Cph, Copenhagen
    url: http://altcph.dk/2008/
lead: |
  Generative plotter drawings
content: |
  Reviving an old Roland plotter, i programmed it to doodle in Processing. 
  It took a few months, but it eventually ended up doodling the same way I do myself during long sedentary phone conversations.
  It has since been updated to run from an embedded Arduino chip.
  The complexity of the doodles is higher than i usually do them by hand and look slightly manic.
  Before starting up a doodle, the plotter has to be loaded with paper, and the button pressed. The plotter will describe itself, and plot a start price. It doodles until stopped, occasionally raising the price at a rate of 12 € an hour.
  When stopped, it signs and numbers the drawing.
  The resulting sheet is sold as a unique pen drawing.
  The plotter has been doodling away for some time at Halfmachine, and has been exhibited at the Alt_Cph opening, curated by Stine Hebert and Mikrogalleriet.
  Thanks to Jacob Sikker Remin from Mikrogalleriet for helping me with the project. Thanks to the guys at Illutron for helping me cram version 2.0 into an arduino. And to Peet from Black Box Gallery, who put it up in Brunnhofer Galerie in Linz parallel to Ars Electronica 2010.