title: Getting Back in the Whole
tags: Music, Performance, Videography, 3D Stereography, Generative, Set Design, Featured, Quartz Composer
partners: Deborah Vlaeymans
client: IN-TRANSIT
date: December 2012
materials: Videoprojectors, stereographic software, 3D glasses
lead: DIY 3D cinema for music performance
photocredits: Ole Kristensen
appearances: 
  - 
    date: Dec 21 2012
    occasion: Performance 
    place: Warehouse 9, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: Dec 01 2012
    occasion: Performance 
    place: CafeTeatret, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: Nov 11 2012
    occasion: Performance
    place: Kunsthallen Nikolaj, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: October 22 2012
    occasion: Performance 
    place: Københavns Musikteater, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: October 2 2012
    occasion: Release 
    place: Science and Cocktails, Christiania
    url: http://www.in-transit.org/2012

content: |
  A friend got obsessed with the socalled Maya Prophecy. This motivated a music performance about a possible end of the world. We travelled to Yucatan to meet the Mayas. I brought along a 3D video camera. They told us that the roumors of armageddon were highly exaggerated.
  
  Deborah Vlaeymans composed the music and performed the songs. I created a mobile 3D cinema, that could travel Copenhagen on a cargo bike.
  
  We combined the stereoscopic illusion of depth with realtime stereographic animations.