title: Getting Back in the Whole
tags: Music, Performance, Videography, 3D Stereography, Generative, Set Design, Featured, Quartz Composer
partners: Deborah Vlaeymans
client: IN-TRANSIT
date: December 2012
project_url: http://www.in-transit.org/2012
materials: Videoprojectors, stereographic software, 3D glasses
lead: DIY 3D cinema for music performance
photocredits: Ole Kristensen
appearances: 
  - 
    date: Dec 21 2012
    occasion: Performance 
    place: Warehouse 9, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: Dec 01 2012
    occasion: Performance 
    place: CafeTeatret, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: Nov 11 2012
    occasion: Performance
    place: Kunsthallen Nikolaj, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: October 22 2012
    occasion: Performance 
    place: Københavns Musikteater, Copenhagen
    url: http://www.in-transit.org/2012
  - 
    date: October 2 2012
    occasion: Release 
    place: Science and Cocktails, Christiania
    url: http://www.in-transit.org/2012

content: |
  In january 2012 I travelled to the Yucatan peninsula with Deborah Vlaeymans. We brought along a 3D camera and a question for the Mayas: Did they believe the world would end on December 21st? The answer was fortunately no. 
  
  Our travel and stereographic films formed the basis of a series of 3D music performances in Copenhagen. I created a mobile 3D cinema, that travelled the city on a cargo bike. 
  
  The stereoscopic films were combined with realtime stereographic animations. The show ran from qLab using Quartz Composer patches to integrate playback and animations. Our DIY projection setup was RealD compatible, and the audience could use the regular glasses from the cinema.
  
  In our travels and the research we learned a lot, not just about how to work with stereoscopic content and the intricate details of the ancient Mayan calendar. The Mayans we met lived very modest lives in small villages among the ancient ruins. They earned next to nothing from the vast tourist groups visiting their heritage on daytrips. The tax-exempt all-inclusive hotels in Cancun made sure to insource all revenue generating activities.
  
  The Yucatan is a beatiful place, and the Mayan heritage is breathtaking. If you go there, please get out and about and stay at locally owned hotels, it made our trip so much more rewarding.
