title: Stop Motion
tags: Installation, Infrared Tracking, Screen-based, Photography, Interactive, OpenFrameworks
partners: Jonas Jongejan
date: May 2008
materials: Infrared camera, DSLR camera, bespoke software.
googlecode: stopmotion
lead: Photographic Video Installation.  
photocredits: Frederik Hilmer and Jonas Jongejan
appearances: 
  - 
    date: Nov 2008
    occasion: Zirkulation Festival 
    place: Baghold, Copenhagen
    url: #
  - 
    date: Sept 2008
    occasion: New Media Meeting 3 
    place: Norrköping, Sweden
    url: http//www.newmediameeting.se/#img_title:title.php?str=artists^lb:media.php?type=image&table=artists&id=20&n=0^lt:navigation.php^rb:artists.php?id=20^rt:artists.php?part=navigation&id=2
  - 
    date: Sept 2008
    occasion: Pecha Kucha #008 
    place: Brorsons Church, Copenhagen
    url: http://www.pechakucha.dk/
  - 
    date: May 2008
    occasion: LED Monolith 
    place: re:new festival, Copenhagen Main Square
    url: http://www.re-new.dk/2008/index.php?pid=57

content: |
  An interactive photo installation created for a 4,5 x 8 meter LED monolith that works fine on a projection. Combining infrared tracking of a normal light bulb and still images, to index photos of audience in a database according to bulb position within the picture frame. When participating audience moves the bulb within the field of view, the screen flickers through previous images of other people having had the bulb at the same position. When someone moves the bulb to an unihabited spot with no previous images, it will flash and that person will now be shown when the bulb is put in the same position.

  Jonas and i sketched up the installation in a few days for re:new 2008, on a very short notice. First iteration was done in processing, but with memory issues. Despite that it ended up having a playful and informal presence in the Copenhagen Main Square.

  We have since then been invited to New Media Meeting 03, where we decided to port the software into open frameworks, and spent two days bashing a Nikon D80 into submission. The installation ran smoothly.